import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { cancelAppointment, createAppointment, createBlock, deleteBlock, getAllAppointments, getBarbers, getBlocks, getClients, getServices, updateAppointment } from '../../api/data'
import { AppointmentCard, formatDateTime } from '../../components/AppointmentCard'
import { Notice } from '../../components/Notice'
import { useNavigate } from 'react-router-dom'

function localDateString(date = new Date()) { return new Intl.DateTimeFormat('en-CA', { year: 'numeric', month: '2-digit', day: '2-digit' }).format(date) }

export function DashboardPage() {
  const navigate = useNavigate(); const qc = useQueryClient()
  const [date, setDate] = useState(localDateString())
  const [selectedBarber, setSelectedBarber] = useState<number | null>(null)
  const [showBlock, setShowBlock] = useState(false); const [blockStart, setBlockStart] = useState('13:00'); const [blockEnd, setBlockEnd] = useState('14:00'); const [reason, setReason] = useState('')
  const [showManual, setShowManual] = useState(false); const [manualClientId, setManualClientId] = useState<number | null>(null); const [manualClient, setManualClient] = useState(''); const [manualPhone, setManualPhone] = useState(''); const [manualService, setManualService] = useState<number | null>(null); const [manualTime, setManualTime] = useState('09:00')
  const [rescheduleTarget, setRescheduleTarget] = useState<number | null>(null); const [rescheduleDate, setRescheduleDate] = useState(date); const [rescheduleTime, setRescheduleTime] = useState('09:00')

  const barbers = useQuery({ queryKey: ['barbers'], queryFn: getBarbers })
  const activeBarber = selectedBarber ?? barbers.data?.[0]?.id ?? 0
  const appointments = useQuery({ queryKey: ['appointments', date, activeBarber], queryFn: () => getAllAppointments(date, activeBarber), enabled: Boolean(activeBarber) })
  const services = useQuery({ queryKey: ['services'], queryFn: getServices })
  const clients = useQuery({ queryKey: ['clients'], queryFn: getClients })
  const blocks = useQuery({ queryKey: ['blocks', date, activeBarber], queryFn: () => getBlocks(activeBarber, date), enabled: Boolean(activeBarber) })
  const cancel = useMutation({ mutationFn: cancelAppointment, onSuccess: () => qc.invalidateQueries({ queryKey: ['appointments'] }) })
  const complete = useMutation({ mutationFn: (id: number) => updateAppointment(id, { status: 'completed' }), onSuccess: () => qc.invalidateQueries({ queryKey: ['appointments'] }) })
  const reschedule = useMutation({ mutationFn: () => updateAppointment(rescheduleTarget!, { starts_at: `${rescheduleDate}T${rescheduleTime}:00` }), onSuccess: async () => { await qc.invalidateQueries({ queryKey: ['appointments'] }); setRescheduleTarget(null) } })
  const blockMutation = useMutation({ mutationFn: () => createBlock({ barber_id: activeBarber, starts_at: `${date}T${blockStart}:00`, ends_at: `${date}T${blockEnd}:00`, reason }), onSuccess: async () => { await qc.invalidateQueries({ queryKey: ['blocks'] }); await qc.invalidateQueries({ queryKey: ['availability'] }); setShowBlock(false); setReason('') } })
  const deleteBlockMutation = useMutation({ mutationFn: deleteBlock, onSuccess: () => qc.invalidateQueries({ queryKey: ['blocks'] }) })
  const manualMutation = useMutation({ mutationFn: () => createAppointment({ barber_id: activeBarber, service_id: manualService ?? services.data?.find(s => s.is_active)?.id ?? 0, starts_at: `${date}T${manualTime}:00`, ...(manualClientId ? { client_id: manualClientId } : { client_name: manualClient.trim(), client_phone: manualPhone.trim() || undefined }) }), onSuccess: async () => { await qc.invalidateQueries({ queryKey: ['appointments'] }); await qc.invalidateQueries({ queryKey: ['clients'] }); setShowManual(false); setManualClientId(null); setManualClient(''); setManualPhone('') } })
  const visibleBlocks = useMemo(() => blocks.data ?? [], [blocks.data])
  const shiftDate = (delta: number) => { const d = new Date(`${date}T12:00:00`); d.setDate(d.getDate() + delta); setDate(localDateString(d)) }

  function openReschedule(id: number) { setRescheduleTarget(id); setRescheduleDate(date); setRescheduleTime('09:00') }

  return <section><div className="section-heading"><div><div className="eyebrow">ПАНЕЛЬ БАРБЕРА</div><h1>Расписание</h1></div><button className="ghost" onClick={() => navigate('/barber/more')}>Настройки</button></div><div className="date-switch"><button className="ghost" onClick={() => shiftDate(-1)}>←</button><input type="date" value={date} onChange={e => setDate(e.target.value)} /><button className="ghost" onClick={() => shiftDate(1)}>→</button></div><label className="field"><span>Мастер</span><select value={activeBarber} onChange={e => setSelectedBarber(Number(e.target.value))}>{barbers.data?.map(b => <option key={b.id} value={b.id}>{b.display_name}</option>)}</select></label><div className="action-grid"><button className="card action-card" onClick={() => setShowManual(true)}><b>+ Запись</b><span className="muted">вручную</span></button><button className="card action-card" onClick={() => setShowBlock(true)}><b>⛔ Блок</b><span className="muted">закрыть время</span></button></div>{appointments.isLoading ? <p className="muted">Загрузка…</p> : <div className="stack">{appointments.data?.map(a => <AppointmentCard key={a.id} appointment={a} staff onCancel={() => cancel.mutate(a.id)} onComplete={() => complete.mutate(a.id)} onReschedule={() => openReschedule(a.id)} />)}</div>}{!appointments.isLoading && !appointments.data?.length && <Notice>На этот день записей нет.</Notice>}{(cancel.error || complete.error || reschedule.error) && <p className="error">{(cancel.error ?? complete.error ?? reschedule.error)?.message}</p>}{visibleBlocks.length > 0 && <><h2>Блокировки</h2><div className="stack">{visibleBlocks.map(block => <div className="card compact-row" key={block.id}><div><b>{formatDateTime(block.starts_at).time}–{formatDateTime(block.ends_at).time}</b><p className="muted">{block.reason || 'Без причины'}</p></div><button className="ghost small-danger" disabled={deleteBlockMutation.isPending} onClick={() => deleteBlockMutation.mutate(block.id)}>Удалить</button></div>)}</div></>}

    {showManual && <div className="modal-backdrop" onClick={() => setShowManual(false)}><div className="modal" onClick={e => e.stopPropagation()}><div className="section-heading"><h2>Новая запись</h2><button className="ghost" onClick={() => setShowManual(false)}>×</button></div><div className="stack"><label className="field"><span>Клиент</span><select value={manualClientId ?? ''} onChange={e => { const value = e.target.value; if (value) { const id = Number(value); setManualClientId(id); const c = clients.data?.find(x => x.id === id); setManualClient(c?.name ?? ''); setManualPhone(c?.phone ?? '') } else { setManualClientId(null); setManualClient(''); setManualPhone('') } }}><option value="">Новый клиент</option>{clients.data?.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{!manualClientId && <><label className="field"><span>Имя</span><input value={manualClient} onChange={e => setManualClient(e.target.value)} placeholder="Имя клиента" autoFocus /></label><label className="field"><span>Телефон</span><input value={manualPhone} onChange={e => setManualPhone(e.target.value)} placeholder="Необязательно" /></label></>}<label className="field"><span>Услуга</span><select value={manualService ?? services.data?.find(s => s.is_active)?.id ?? ''} onChange={e => setManualService(Number(e.target.value))}>{services.data?.filter(s => s.is_active).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field"><span>Время</span><input type="time" value={manualTime} onChange={e => setManualTime(e.target.value)} /></label><button className="primary" disabled={(!manualClientId && !manualClient.trim()) || !activeBarber || manualMutation.isPending} onClick={() => manualMutation.mutate()}>{manualMutation.isPending ? 'Создаём…' : 'Создать запись'}</button>{manualMutation.error && <p className="error">{manualMutation.error.message}</p>}</div></div></div>}
    {showBlock && <div className="modal-backdrop" onClick={() => setShowBlock(false)}><div className="modal" onClick={e => e.stopPropagation()}><div className="section-heading"><h2>Заблокировать время</h2><button className="ghost" onClick={() => setShowBlock(false)}>×</button></div><div className="stack"><div className="card tiny-note">Выбран мастер: <b>{barbers.data?.find(b => b.id === activeBarber)?.display_name}</b></div><div className="two-cols"><label className="field"><span>Начало</span><input type="time" value={blockStart} onChange={e => setBlockStart(e.target.value)} /></label><label className="field"><span>Конец</span><input type="time" value={blockEnd} onChange={e => setBlockEnd(e.target.value)} /></label></div><label className="field"><span>Причина</span><input value={reason} onChange={e => setReason(e.target.value)} placeholder="Обед, личные дела…" /></label><button className="primary" disabled={blockMutation.isPending || !activeBarber} onClick={() => blockMutation.mutate()}>{blockMutation.isPending ? 'Сохраняем…' : 'Заблокировать'}</button>{blockMutation.error && <p className="error">{blockMutation.error.message}</p>}</div></div></div>}
    {rescheduleTarget && <div className="modal-backdrop" onClick={() => setRescheduleTarget(null)}><div className="modal" onClick={e => e.stopPropagation()}><div className="section-heading"><h2>Перенести запись</h2><button className="ghost" onClick={() => setRescheduleTarget(null)}>×</button></div><div className="stack"><label className="field"><span>Дата</span><input type="date" value={rescheduleDate} onChange={e => setRescheduleDate(e.target.value)} /></label><label className="field"><span>Время</span><input type="time" value={rescheduleTime} onChange={e => setRescheduleTime(e.target.value)} /></label><button className="primary" disabled={reschedule.isPending} onClick={() => reschedule.mutate()}>{reschedule.isPending ? 'Переносим…' : 'Перенести'}</button>{reschedule.error && <p className="error">{reschedule.error.message}</p>}</div></div></div>}
  </section>
}
