-- Production migration note:
-- CREATE EXTENSION IF NOT EXISTS btree_gist;
-- ALTER TABLE appointments ADD CONSTRAINT appointments_no_overlap
-- EXCLUDE USING gist (
--   barber_member_id WITH =,
--   tstzrange(starts_at, ends_at, '[)') WITH &&
-- ) WHERE (status IN ('pending', 'confirmed'));
